routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth', 'balance')->group(function () {
    Route::get('/', 'CurrencyController@index')->name('home');
    Route::get('/home', 'CurrencyController@index');

    Route::prefix('currencies')->name('currencies.')->group(function () {
        Route::get('/', 'CurrencyController@index')->name('index');
        Route::middleware('client')->get('/{currency}', 'CurrencyController@show')->name('show');
    });

    Route::middleware('client')->prefix('transactions')->name('transactions.')->group(function () {
        Route::get('/{currency?}', 'TransactionController@index')->name('index');
        Route::get('/create/{currency}', 'TransactionController@create')->name('create');
        Route::post('/', 'TransactionController@store')->name('store');
        Route::patch('/{currency}/{transaction?}', 'TransactionController@update')->name('update');
        Route::get('/sell/{currency}', 'TransactionController@sell')->name('sell');
    });

    Route::middleware('admin')->resource('users', 'UserController')->except(['show']);

    Route::prefix('account')->name('account.')->group(function () {
        Route::get('/edit', 'UserController@editAccount')->name('edit');
        Route::patch('/{user}', 'UserController@updateAccount')->name('update');
    });

    Route::middleware('client')->get('/wallet', 'WalletController@index')->name('wallet');
});

Route::prefix('api')->name('api.')->group(function () {
    Route::get('/get-price/{fsym}', function ($fsym) {
        $api = new App\API;
        return $api->getPrice($fsym);
    })->name('get-price');
});

Auth::routes();

resources/views/partials/flash-message.blade.php
<div class="row">
    <div class="col-12">
        @if(Session::has('message'))
            <div class="alert alert-success" role="alert">
                <p class="m-0">{{ Session::get('message') }}</p>
            </div>
        @elseif(Session::has('error'))
            <div class="alert alert-danger" role="alert">
                <p class="m-0">{{ Session::get('error') }}</p>
            </div>
        @endif
    </div>
</div>

resources/views/partials/sidebar.blade.php
<nav class="hidden position-fixed d-flex flex-column justify-content-between p-3" id="sidebar">
    <div id="toggleNav" class="justify-content-center align-items-center">
        <i class="fas fa-lg fa-bars"></i>
    </div>
    <div id="navTop">
        <a href="{{ route('home') }}">
            <div class="d-flex justify-content-center align-items-center flex-wrap border-bottom pb-5">
                <i class="far fa-money-bill-alt fa-3x" id="logoIcon"></i>
                <span class="ml-2" id="logotype">BitChest</span>
            </div>
        </a>
        <ul class="my-5 p-0">
            <a href="{{ route('currencies.index') }}">
                <li class="sidebar-item d-flex align-items-center mb-2 @if($section == 'currencies') active @endif">
                    <i class="fab fa-lg fa-bitcoin"></i>
                    <span class="text-capitalize ml-2">Les cryptomonnaies</span>
                </li>
            </a>
            @if (Auth::user()->status == 'client')
                <a href="{{ route('wallet') }}">
                    <li class="sidebar-item d-flex align-items-center mb-2 @if($section == 'wallet') active @endif">
                        <i class="fas fa-lg fa-wallet"></i>
                        <span class="text-capitalize ml-2">Mon portefeuille</span>
                    </li>
                </a>
            @endif
            @if (Auth::user()->status == 'admin')
                <a href="{{ route('users.index') }}">
                    <li class="sidebar-item d-flex align-items-center mb-2 @if($section == 'users') active @endif">
                        <i class="fas fa-lg fa-users"></i>
                        <span class="text-capitalize ml-2">Les utilisateurs</span>
                    </li>
                </a>
            @endif
            <a href="{{ route('account.edit') }}">
                <li class="sidebar-item d-flex align-items-center mb-2 @if($section == 'account') active @endif">
                    <i class="fas fa-lg fa-user-circle"></i>
                    <span class="text-capitalize ml-2">Mon compte</span>
                </li>
            </a>
        </ul>
        @if (Auth::user()->status == 'client')
            <div>
                <span class="text-capitalize">Mon solde : </span>
                <span id="balance">{{ session('balance') }} {{ config('currency')['symbol'] }}</span>
            </div>
        @endif
    </div>
    <div id="navBottom" class="d-flex justify-content-between">
        <a href="{{ route('logout') }}" class="flex-grow-1" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <div class="sidebar-item d-flex align-items-center">
                <i class="fas fa-lg fa-sign-out-alt"></i>
                <span class="text-capitalize ml-2">Déconnexion</span>
            </div>
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
        <div class="sidebar-item align-items-center justify-content-end flex-grow-1" id="closeNav">
            <i class="fas fa-lg fa-times-circle"></i>
            <span class="text-capitalize ml-2">Fermer</span>
        </div>
    </div>
</nav>