routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth', 'balance')->group(function () {
    Route::get('/', 'CurrencyController@index')->name('home');
    Route::get('/home', 'CurrencyController@index');

    Route::prefix('currencies')->name('currencies.')->group(function () {
        Route::get('/', 'CurrencyController@index')->name('index');
        Route::middleware('client')->get('/{currency}', 'CurrencyController@show')->name('show');
    });

    Route::middleware('client')->prefix('transactions')->name('transactions.')->group(function () {
        Route::get('/{currency?}', 'TransactionController@index')->name('index');
        Route::get('/create/{currency}', 'TransactionController@create')->name('create');
        Route::post('/', 'TransactionController@store')->name('store');
        Route::patch('/{currency}/{transaction?}', 'TransactionController@update')->name('update');
        Route::get('/sell/{currency}', 'TransactionController@sell')->name('sell');
    });

    Route::middleware('admin')->resource('users', 'UserController')->except(['show']);

    Route::prefix('account')->name('account.')->group(function () {
        Route::get('/edit', 'UserController@editAccount')->name('edit');
        Route::patch('/{user}', 'UserController@updateAccount')->name('update');
    });

    Route::middleware('client')->get('/wallet', 'WalletController@index')->name('wallet');
});

Route::prefix('api')->name('api.')->group(function () {
    Route::get('/get-price/{fsym}', function ($fsym) {
        $api = new App\API;
        return $api->getPrice($fsym);
    })->name('get-price');
});

Auth::routes();

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Currency;
use App\Transaction;
use App\User;
use App\API;

class TransactionController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct(Request $request)
    {
        if (Str::contains($request->path(), 'create')) {
            view()->composer('layouts.layout', function ($view) {
                $view->with('section', 'currencies');
            });
        } else {
            view()->composer('layouts.layout', function ($view) {
                $view->with('section', 'wallet');
            });
        }

        date_default_timezone_set('Europe/Paris'); // Set timezone
    }

    /**
     * Display the user's transactions (all of them or by currency).
     */
    public function index(Currency $currency = null)
    {
        $transactions = $currency // If a currency is specified :
            ? Auth::user()->transactions()->where('currency_id', $currency->id)->get() // Get the uder's transactions corresponding to this currency
            : Auth::user()->transactions; // Else, get all of their transactions

        // Format a few fields of the transactions
        $transactions = $transactions->map(function ($transaction) {
            // Round figures to make them more readable
            $transaction->quantity = round($transaction->quantity, 4);

            $transaction->purchase_price = round($transaction->purchase_price, 4);

            $transaction->selling_price = round($transaction->selling_price, 4);

            return $transaction;
        });

        return view('transactions.index', ['transactions' => $transactions, 'currency' => $currency]);
    }

    /**
     * Display the user's transactions corresponding to a currency in order to sell them.
     */
    public function sell(Currency $currency)
    {
        $transactions = Auth::user() // Logged in user
            ->transactions() // Get his transactions
            ->where([ // Filter by :
                'sold' => false, // Unsold ones
                'currency_id' => $currency->id // Corresponding to the specified currency
            ])
            ->get();

        // Format a few fields of the transactions
        $transactions = $transactions->map(function ($transaction) {
            $transaction->purchase_price = round($transaction->purchase_price, 4); // Round figures to make them more readable
            return $transaction;
        });

        $title = 'Vente de ' . $currency->name;

        return view('transactions.sell', ['transactions' => $transactions, 'title' => $title]);
    }

    /**
     * Show the form for buying a currency.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Currency $currency)
    {
        $title = 'Acheter du ' . $currency->name;

        return view('transactions.create', ['title' => $title, 'currency' => $currency]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, API $api)
    {
        $attributes = $request->all(); // Get form inputs data

        $attributes['user_id'] = Auth::id(); // Get user's id to insert it
        $attributes['purchase_date'] = Carbon::now()->toDateTimeString(); // Get current datetime to insert it
        $attributes['purchase_price'] = $api->getPrice($attributes['currency_api_id']); // Get current rate to insert it

        // Calculate quantity or amount depending on which buying option the user chose
        if ($attributes['buying_option'] == 'amountBuyingInput') {
            $attributes['quantity'] = $attributes['amount'] / $attributes['purchase_price'];
        } elseif ($attributes['buying_option'] == 'quantityBuyingInput') {
            $attributes['amount'] = $attributes['quantity'] * $attributes['purchase_price'];
        }

        $transaction = Transaction::create($attributes); // Create transaction in DB

        return redirect()
            ->route('wallet')
            ->with('message', 'La transaction a bien été effectuée. Vous avez acheté : ' . round($transaction->quantity, 6) . ' ' . $transaction->currency->name . ' pour un montant de ' . $transaction->amount . ' ' . config('currency')['symbol'] . '.');
    }

    /**
     * Sell one specified transaction or all those of a currency.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Currency $currency, Transaction $transaction = null, Request $request, API $api)
    {
        if ($transaction) {
            $transaction->sold = 1;
            $transaction->selling_amount = round($request->selling_amount, 2);
            $transaction->selling_price = $request->selling_price;
            $transaction->selling_date = Carbon::now();

            $transaction->save();

            return redirect()
                ->route('wallet')
                ->with('message', 'La transaction a bien été effectuée. Vous avez vendu : ' . floatval($transaction->quantity) . ' ' . $currency->name . ' pour un montant de ' . round($request->selling_amount, 2) . ' ' . config('currency')['symbol'] . '.');
        } else {
            $quantity_total = 0;
            $selling_amount_total = 0;

            $transactions = Transaction::where([
                'currency_id' => $currency->id,
                'user_id' => Auth::id()
            ]);

            $transactions->update([
                'sold' => 1,
                'selling_price' => $api->getPrice($currency->api_id),
                'selling_date' => Carbon::now()
            ]);

            foreach ($transactions->get() as $transaction) {
                $transaction->selling_amount = $transaction->selling_price * $transaction->quantity;
                $transaction->save();

                $quantity_total += $transaction->quantity;
                $selling_amount_total += $transaction->selling_amount;
            }

            return redirect()
                ->route('wallet')
                ->with('message', 'La transaction a bien été effectuée. Vous avez vendu : ' . floatval($quantity_total) . ' ' . $currency->name . ' pour un montant de ' . round($selling_amount_total, 2) . ' ' . config('currency')['symbol'] . '.');
        }
    }
}

resources/views/transactions/create.blade.php
@extends('layouts.layout')

@section('title', $title)

@section('content')
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Achat {{ $currency->name }}</h1>
            <div class="d-flex justify-content-center my-4">
                <a class="btn btn-sm btn-outline-secondary" href="{{ route('currencies.index') }}" role="button">Retour liste</a>
                <a class="btn btn-sm btn-primary ml-3" href="{{ route('currencies.show', $currency->id) }}" role="button">Historique</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="alert alert-warning" role="alert">
                <span class="font-weight-bold">Attention :</span> toutes les informations de paiement sont calculées par rapport au cours de la monnaie au moment où vous êtes arrivé(e) sur cette page. Pour actualiser ces informations en fonction du cours le plus récent, cliquez sur le bouton <span class="font-weight-bold">"Rafraîchir le cours actuel"</span> ci-dessous.
            </div>
            <div class="alert alert-info" role="alert">
                Cours actuel du {{ $currency->name }} :
                <span class="font-weight-bold">
                    <span id="currentRate"></span> {{ config('currency')['symbol'] }}
                </span>
                <button type="button" id="refreshRate" class="btn btn-info text-white ml-2" data-toggle="tooltip" data-placement="top" title="Rafraîchir le cours actuel">
                    <i class="fas fa-sync"></i>
                </button>
            </div>
        </div>
        <div class="col-12">
            <form id="buyingForm" action="{{ route('transactions.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="buying_option">Choisissez une méthode d'achat :</label>
                    <div class="form-check">
                        <input class="form-check-input buying_options" type="radio" name="buying_option" id="buy_by_amount" value="amountBuyingInput" required>
                        <label class="form-check-label" for="buy_by_amount">Investir une certaine somme</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input buying_options" type="radio" name="buying_option" id="buy_by_quantity" value="quantityBuyingInput" required>
                        <label class="form-check-label" for="buy_by_quantity">Acheter une certaine quantité</label>
                    </div>
                </div>
                <div class="form-group buying-inputs" id="amountBuyingInput">
                    <label for="amount">Somme à investir</label>
                    <input type="number" class="form-control" id="amount" name="amount" max="999999" aria-describedby="amountTotal">
                    <small class="form-text text-muted">
                        Total de {{ $currency->name }} acquis :
                        <span id="quantityTotal" class="font-weight-bold"></span>
                    </small>
                </div>
                <div class="form-group buying-inputs" id="quantityBuyingInput">
                    <label for="quantity">Quantité à acheter</label>
                    <input type="number" class="form-control" id="quantity" name="quantity" step="0.001" aria-describedby="quantityTotal">
                    <small class="form-text text-muted">
                        Total à payer :
                        <span class="font-weight-bold">
                            <span id="amountTotal"></span> {{ config('currency')['symbol'] }}
                        </span>
                    </small>
                </div>
                <input type="hidden" name="currency_id" value="{{ $currency->id }}">
                <input type="hidden" name="currency_api_id" value="{{ $currency->api_id }}">
                <button type="submit" class="btn btn-primary">Confirmer l'achat</button>
            </form>
        </div>
    </div>
@endsection

@section('JS')
    <script>
        let currentRate;
        const refreshIcon = $('#refreshRate .fa-sync');

        function calcAndDisplayQuantity() {
            const quantityTotal = $('#amount').val() / currentRate;
            $('#quantityTotal').text(quantityTotal.toFixed(6));
        }

        function calcAndDisplayAmount() {
            const amountTotal = $('#quantity').val() * currentRate;
            $('#amountTotal').text(amountTotal.toFixed(2));
        }

        function getAndDisplayCurrentRate() {
            // Get current rate from the API
            $.get({
                url: '{{ route('api.get-price', $currency->api_id) }}',
                success: function(data) {
                    currentRate = data;

                    // Refresh payment infos
                    calcAndDisplayQuantity();
                    calcAndDisplayAmount();

                    $('#currentRate').text(currentRate); // Refresh rate display

                    // Calculate max value for quantity input (total amount mustn't exceed 999999)
                    const qtyMax = 999999 / currentRate;
                    $('#quantity').attr('max', qtyMax);

                    refreshIcon.removeClass('fa-spin'); // Stop icon spinning
                }
            })
            .fail(function(error) {
                console.log(error);
            });
        }

        // On page load
        $(function() {
            getAndDisplayCurrentRate();

            // On click on refresh button
            $('#refreshRate').click(function() {
                refreshIcon.addClass('fa-spin'); // Make the icon spin during the request
                getAndDisplayCurrentRate(); // Refresh payment info
            });

            // Display and hide inputs
            $('.buying_options').change(function() {
                const input = $(this).val();
                $(`.buying-inputs#${input}`).show();
                $(`.buying-inputs#${input} input[type="number"]`).attr('required', 'required');
                $(`.buying-inputs:not(#${input})`).hide();
                $(`.buying-inputs:not(#${input}) input[type="number"]`).removeAttr('required');
            });

            // When the user types in an input
            $('input[type="number"]').on('input', function() {
                if ($(this).is('#amount')) {
                    calcAndDisplayQuantity();
                } else if ($(this).is('#quantity')) {
                    calcAndDisplayAmount();
                }
            });

            // Confirm before form submitting
            $("#buyingForm").submit(function () {
                return confirm("Confimer l'achat ?");
            });
        });
    </script>
@endsection

resources/views/transactions/sell.blade.php
@extends('layouts.layout')

@section('title', $title)

@section('content')
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Vendre du {{ $transactions->first()->currency->name }}</h1>
            <div class="d-flex justify-content-center my-4">
                <a class="btn btn-sm btn-outline-secondary" href="{{ route('wallet') }}" role="button">Retour au portefeuille</a>
                <form class="selling-form" action="{{ route('transactions.update', $transactions->first()->currency->id) }}" method="POST">
                    @method('PATCH')
                    @csrf
                    <input class="btn btn-sm btn-primary ml-3" role="button" type="submit" value="Vendre tout">
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="alert alert-warning" role="alert">
                <span class="font-weight-bold">Attention :</span> toutes les informations de paiement sont calculées par rapport au cours de la monnaie au moment où vous êtes arrivé(e) sur cette page. Pour actualiser ces informations en fonction du cours le plus récent, cliquez sur le bouton <span class="font-weight-bold">"Rafraîchir le cours actuel"</span> ci-dessous.
            </div>
            <div class="alert alert-info" role="alert">
                Cours actuel du {{ $transactions->first()->currency->name }} :
                <span class="font-weight-bold">
                    <span id="currentRate"></span> {{ config('currency')['symbol'] }}
                </span>
                <button type="button" id="refreshRate" class="btn btn-info text-white ml-2" data-toggle="tooltip" data-placement="top" title="Rafraîchir le cours actuel">
                    <i class="fas fa-sync"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="datatable custom">
                <thead>
                    <tr>
                        <th>Quantité</th>
                        <th>Cours à l'achat</th>
                        <th>Total dépensé</th>
                        <th>Total de vente potentiel</th>
                        <th>Plus/Moins-value</th>
                        <th>Date d'achat</th>
                        <th data-orderable="false"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($transactions as $transaction)
                        <tr class="transaction">
                            <td class="quantity">{{ $transaction->quantity + 0 }}</td>
                            <td>{{ str_replace('.', ',', $transaction->purchase_price) }} {{ config('currency')['symbol'] }}</td>
                            <td class="amount">{{ str_replace('.', ',', $transaction->amount) }} {{ config('currency')['symbol'] }}</td>
                            <td><span class="selling-amount"></span> {{ config('currency')['symbol'] }}</td>
                            <td class="increase-col"><span class="increase"></span> {{ config('currency')['symbol'] }}</td>
                            <td>{{ $transaction->purchase_date }}</td>
                            <td>
                                <form class="selling-form" action="{{ route('transactions.update', [$transactions->first()->currency->id, $transaction->id]) }}" method="POST">
                                    @method('PATCH')
                                    @csrf
                                    <input type="hidden" name="selling_amount" value="">
                                    <input type="hidden" name="selling_price" value="">
                                    <input class="btn btn-sm btn-primary" role="button" type="submit" value="Vendre">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('JS')
    <script>
        let currentRate;
        const refreshIcon = $('#refreshRate .fa-sync');
        const transactions = $('.transaction');

        function refreshTransactionInfo() {
            // Loop through transactions to make calculations for all of them
            $.each(transactions, function (i, transaction) {
                const sellingAmount = $(transaction).find('.quantity').text() * currentRate;
                const increase = sellingAmount - parseInt($(transaction).find('.amount').text());

                $(transaction).find('.selling-amount').text(sellingAmount.toFixed(2));
                $(transaction).find('.increase').text(increase.toFixed(2));

                if (increase > 0) {
                    $(transaction).find('.increase-col').addClass('text-success');
                } else {
                    $(transaction).find('.increase-col').addClass('text-danger');
                }

                // Set hidden inputs values for having these values when we sell
                $('input[name="selling_amount"]').val(sellingAmount);
                $('input[name="selling_price"]').val(currentRate);
            });
        }

        function getAndDisplayCurrentRate() {
            // Get current rate from the API
            $.get({
                url: '{{ route('api.get-price', $transactions->first()->currency->api_id) }}',
                success: function(data) {
                    currentRate = data;
                    refreshTransactionInfo(); // Refresh payment infos
                    $('#currentRate').text(currentRate); // Refresh rate display
                    refreshIcon.removeClass('fa-spin'); // Stop icon spinning
                }
            })
            .fail(function(error) {
                console.log(error);
            });
        }

        $(function() {
            $('.datatable.custom').DataTable({
                order: [[4, "desc"]],
                language: {
                    url: "https://cdn.datatables.net/plug-ins/1.10.20/i18n/French.json"
                }
            });

            getAndDisplayCurrentRate(); // On page load

            // On click on refresh button
            $('#refreshRate').click(function() {
                refreshIcon.addClass('fa-spin'); // Make the icon spin during the request
                getAndDisplayCurrentRate(); // Refresh payment info
            });

            // Confirm before form submitting
            $(".selling-form").submit(function () {
                return confirm("Confimer la vente ?");
            });
        });
    </script>
@endsection