routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth', 'balance')->group(function () {
    Route::get('/', 'CurrencyController@index')->name('home');
    Route::get('/home', 'CurrencyController@index');

    Route::prefix('currencies')->name('currencies.')->group(function () {
        Route::get('/', 'CurrencyController@index')->name('index');
        Route::middleware('client')->get('/{currency}', 'CurrencyController@show')->name('show');
    });

    Route::middleware('client')->prefix('transactions')->name('transactions.')->group(function () {
        Route::get('/{currency?}', 'TransactionController@index')->name('index');
        Route::get('/create/{currency}', 'TransactionController@create')->name('create');
        Route::post('/', 'TransactionController@store')->name('store');
        Route::patch('/{currency}/{transaction?}', 'TransactionController@update')->name('update');
        Route::get('/sell/{currency}', 'TransactionController@sell')->name('sell');
    });

    Route::middleware('admin')->resource('users', 'UserController')->except(['show']);

    Route::prefix('account')->name('account.')->group(function () {
        Route::get('/edit', 'UserController@editAccount')->name('edit');
        Route::patch('/{user}', 'UserController@updateAccount')->name('update');
    });

    Route::middleware('client')->get('/wallet', 'WalletController@index')->name('wallet');
});

Route::prefix('api')->name('api.')->group(function () {
    Route::get('/get-price/{fsym}', function ($fsym) {
        $api = new App\API;
        return $api->getPrice($fsym);
    })->name('get-price');
});

Auth::routes();

app/Http/Controllers/WalletController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\API;

class WalletController extends Controller
{
    protected $data;
    protected $api_ids;

    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        view()->composer('layouts.layout', function ($view) {
            $view->with('section', 'wallet');
        });

        $this->api_ids = []; // Init an array for currencies' API IDs (for the API call)
    }

    /**
     * Display the user's wallet.
     */
    public function index(API $api)
    {
        $currencies = Auth::user()
            ->transactions // Get user's transactions
            ->where('sold', 0) // Unsold
            ->groupBy('currency_id') // Group them by currency
            ->map(function ($row) {
                    $this->api_ids[] = $row->first()->currency->api_id; // Fill API IDs array for future API call
                    return [
                        'currency'          => $row->first()->currency,
                        'total_quantity'    => $row->sum('quantity'), // Calculate the total of this currency
                        'total_amount'      => $row->sum('amount') // Calculate the amount the user spent
                    ];
                });

        if ($currencies->isNotEmpty()) {
            $this->data = $api->getMultipleData(implode(',', $this->api_ids)); // Get data from the API

            // Loop through currencies to add data from API
            $currencies = $currencies->map(function ($currency) {
                $api_id = $currency['currency']->api_id;

                $currency['current_rate'] = $this->data[$api_id]['current_rate'];
                $currency['change'] = $this->data[$api_id]['change'];
                $currency['increase'] = round($currency['current_rate'] * $currency['total_quantity'] - $currency['total_amount'], 2); // Compare what the user spent to what they could get if they sold it all to calculate increase/decrease

                return $currency;
            });
        }

        return view('wallet.index', ['currencies' => $currencies]);
    }
}

resources/views/wallet/index.blade.php
@extends('layouts.layout')

@section('title', 'Mon Portefeuille')

@section('content')
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Mon Portefeuille</h1>
            <div class="d-flex justify-content-center my-4">
                <a class="btn btn-sm btn-outline-secondary" href="{{ route('transactions.index') }}" role="button">Voir toutes vos transactions</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            @if ($currencies->isNotEmpty())
                <table class="datatable">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Identifiant</th>
                            <th>Quantité</th>
                            <th>Cours actuel</th>
                            <th>Plus/Moins-value</th>
                            <th data-orderable="false"></th>
                            <th data-orderable="false"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($currencies as $currency)
                            <tr>
                                <td><img src="{{ asset($currency['currency']->logo) }}" alt="Logo {{ $currency['currency']->name }}" class="mr-3">{{ $currency['currency']->name }}</td>
                                <td>{{ $currency['currency']->api_id }}</td>
                                <td>{{ str_replace('.', ',', $currency['total_quantity']) }}</td>
                                <td class="d-flex align-items-center">
                                    {{ str_replace('.', ',', $currency['current_rate']) }} {{ config('currency')['symbol'] }}
                                    @if ($currency['change'] == '+')
                                        <i class="change-caret-up fas fa-2x fa-caret-up ml-2"></i>
                                    @else
                                        <i class="change-caret-down fas fa-2x fa-caret-down ml-2"></i>
                                    @endif
                                </td>
                                @if ($currency['increase'] > 0)
                                    <td class="text-success">
                                @else
                                    <td class="text-danger">
                                @endif
                                    {{ str_replace('.', ',', $currency['increase']) }} {{ config('currency')['symbol'] }}</td>
                                <td><a class="btn btn-sm btn-outline-secondary" href="{{ route('transactions.index', $currency['currency']->id) }}" role="button">Voir les transactions</a></td>
                                <td><a class="btn btn-sm btn-primary" href="{{ route('transactions.sell', $currency['currency']->id) }}" role="button">Vendre</a></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <div class="text-center">
                    Vous ne détenez actuellement aucune cryptomonnaie.<br>Pour en acheter, ça se passe ici :
                    <a class="btn btn-sm btn-primary" href="{{ route('currencies.index') }}" role="button">Liste des cryptomonnaies</a>
                </div>
            @endif
        </div>
    </div>
@endsection